server:
  port: 8001
mybatis:
  type-aliases-package: com.demo.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddb01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 0

#Eureka配置服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
      instance-id: springcloud-provider-dept-hystrix-8001 #修改Eureka上电脑描述信息
      prefer-ip-address: true #显示ip地址

info:
  app.name: springclouddemo-hystrix
  company.name: DLUT